version: "3.1"

services:
  tomcat:
    container_name: tomcats
    image: tomcat:8.5.70-jre8-openjdk-slim
    volumes:
      - ./index.html:/usr/local/tomcat/webapps/ROOT/index.html
    ports:
      - 8088:8080

networks:
  default:
    external:
      name: local-docker-bridge
