spring:
  database:
    datasource:
      hikari:
        maximumPoolSize: 5
database:
  url: http://127.0.0.1:9091
  id: postgres
  password: post123!
  database-ip: localhost
  database-port: 5432
  database-name: dtonic
  database-option:
  database-type: POSTGRES
